### ISSUE TITLE
Content-type mismatch of POST data

### ISSUE THREAD

**Issue by woodb** [cenkalti/github-flask#21]
It looks like the `Content-Type` of `POST` data is [currently set](https://github.com/cenkalti/github-flask/blob/21867e85b20d283ff67df6d96e293c1fb0a9ed13/flask_github.py#L197-L198) to `application/x-www-form-urlencoded`, even though the [data are encoded as JSON](https://github.com/cenkalti/github-flask/blob/21867e85b20d283ff67df6d96e293c1fb0a9ed13/flask_github.py#L202).

I might be missing a nuance of the GitHub API, but should we consider changing this to `application/json` instead to match?

**Comment by woodb** [comment]
By the way, I will gladly file a PR to fix this and #22, but I don't want dig in until PR #19 gets merged @cenkalti, what do you think?

**Comment by woodb** [comment]
So I ended up just adding this to PR #19, along with #22, since I had time :smile_cat:

**Comment by cenkalti** [comment]
:+1:
