### ISSUE TITLE
Migrate to request headers for token authentication

### ISSUE THREAD

**Issue by woodb** [cenkalti/github-flask#22]
It looks like certain parts of the GitHub API don't support the [`access_token` query parameter](https://developer.github.com/v3/oauth/#use-the-access-token-to-access-the-api).

I don't think this is entirely documented, but I noticed that when working with the [GitHub deployments API](https://developer.github.com/v3/repos/deployments/) that the `access_token` query parameter was not working (perhaps a fluke in what is one of the [relatively newer components](https://developer.github.com/changes/2014-01-09-preview-the-new-deployments-api/) to the GitHub API).

I found that by manually passing the `Authorization` header to the `post` method that my requests began to work again.

I propose switching to use the `Authorization` header rather than the `access_token` query parameter (or why not both).

**Comment by cenkalti** [comment]
:+1:
