### ISSUE TITLE
Look for configs in os.environ

### ISSUE THREAD

**Issue by ehfeng** [cenkalti/github-flask#39]
Would be a nice touch to have the app look in the `os.environ` if `app.config` doesn't have the client id and and client secret values.

Similar to how `FLASK_DEBUG` works. I can do the PR—I wanted to open the issue to check if it's in line with how you see this library being used.

**Comment by cenkalti** [comment]
Hi @ehfeng. Thanks for asking before sending the PR.
* Can you tell why do you need this?
* Is there any Flask extension that you know implement this behavior?

**Comment by ehfeng** [comment]
Oh, I don't need this—I can just `os.environ.get`. It just seemed convenient, as [Flask itself](http://flask.pocoo.org/docs/0.12/config/) pulls some configs from the environment.
