### ISSUE TITLE
Add mocking capability

### ISSUE THREAD

**Issue by brizental** [cenkalti/github-flask#40]
I have an app that uses this extension and I want to mock the login function for testing. I was thinking that maybe we could add a a flag saying that the app is in test mode or not, if that is the case, then mock everything. I am willing to implement this :)

**Comment by cenkalti** [comment]
Hello @brizental. Which function/method do you want to mock? Can you solve your problem using `unittest.mock` module?

**Comment by brizental** [comment]
I need to mock the `authorize` method and the `get` method, to login and get user info. I can use `unittest.mock` , but I thought it would be useful to have that built into the extension, instead of only having it in my app. Of course then we would have to mock every request to the GitHub API, not only the ones that I need. What do you think?

**Comment by cenkalti** [comment]
Sorry @brizental, I don't want to add this functionality to the extension. I find `unittest.mock` more suitable for the job.

**Comment by brizental** [comment]
That's fine @cenkalti . Thanks for the quicl answer :)
