### ISSUE TITLE
About pagination of github.get

### ISSUE THREAD

**Issue by yiwu1** [cenkalti/github-flask#52]
@cenkalti Sounds great example! Do you have API reference document with detailed introduction about flask_github.GitHub.get ? As you know it only returns 30 records by default in first page, trying to leverage this method for all pagination records instead to write own.

**Comment by cenkalti** [comment]
If you pass `all_pages=True`, the library will fetch all of the pages.

https://github.com/cenkalti/github-flask/blob/a65bae8dc533077902dc9bad1618ee6073a020a3/flask_github.py#L250

**Comment by yiwu1** [comment]
:thumbsup:

**Comment by yiwu1** [comment]
@cenkalti When I call request(self, method, resource, all_pages=False, **kwargs), terminal console will get 404: not found if GitHub API return empty sometime, I know it goes to following lines:
        if not is_valid_response(response):
            raise GitHubError(response)  
Is it possible to catch the GitHubError exception like 404, 409 ? And how to catch different exception so that I can do conditional check? for example 
try: request()
except **[how to get 404 here]**: do something
 Thanks!

**Comment by cenkalti** [comment]
You can capture `GitHubError` and inspect status code attribute.

```py
try:
    ...
except GitHubError as e:
    if e.response.status_code == 404:
        # handle 404
    raise
```

**Comment by yiwu1** [comment]
@cenkalti Thanks for your reply! I tried but not work as expected here:
    except GitHubError as e:
NameError: global name 'GitHubError' is not defined

**Comment by yiwu1** [comment]
:+1: :sparkles:  :tada:  :octocat:
